/** @type {import('tailwindcss').Config} */
// Tokens mirror design-reference DESIGN.md (Crimson Heritage). Keep in sync with
// src/theme/tokens.ts, which re-exports the raw values for JS-side consumers
// (icon colors, shadows, navigation options) that can't use className.
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        surface: '#fcf9f8',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-surface': '#1c1b1b',
        'on-surface-variant': '#564242',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        outline: '#897172',
        'outline-variant': '#dcc0c0',
        'surface-tint': '#a23b47',
        // primary = 텍스트/아이콘용, primary-container = 버튼/배지용
        primary: '#670d1e',
        'on-primary': '#ffffff',
        'primary-container': '#862633',
        'on-primary-container': '#ff9ea3',
        'inverse-primary': '#ffb3b6',
        secondary: '#735c00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed65b',
        'on-secondary-container': '#745c00',
        tertiary: '#34332e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#4b4944',
        'on-tertiary-container': '#bcb8b2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdada',
        'primary-fixed-dim': '#ffb3b6',
        'on-primary-fixed': '#40000c',
        'on-primary-fixed-variant': '#832331',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#e6e2db',
        'tertiary-fixed-dim': '#cac6bf',
        'on-tertiary-fixed': '#1c1c17',
        'on-tertiary-fixed-variant': '#484742',
        background: '#fcf9f8',
        'on-background': '#1c1b1b',
        'surface-variant': '#e5e2e1',
      },
      spacing: {
        unit: 4,
        xs: 4,
        sm: 8,
        gutter: 12,
        md: 16,
        lg: 24,
        xl: 32,
        'container-padding': 20,
      },
      borderRadius: {
        sm: 4,
        DEFAULT: 8,
        md: 12,
        lg: 16,
        xl: 24,
        full: 9999,
      },
      // React Native picks a font file per weight, so weight lives in the family
      // name rather than in a `font-bold` utility.
      fontFamily: {
        sans: ['NotoSansKR_400Regular'],
        'sans-medium': ['NotoSansKR_500Medium'],
        'sans-semibold': ['NotoSansKR_600SemiBold'],
        'sans-bold': ['NotoSansKR_700Bold'],
      },
      // letterSpacing converted from em to px at each token's own font size.
      // lineHeight는 반드시 단위를 붙인다. 숫자만 쓰면 배수로 해석된다.
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.64px' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.24px' }],
        'headline-sm': ['20px', { lineHeight: '28px' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.6px' }],
      },
    },
  },
  plugins: [],
};
